version:  '3.8'
services:
    database:
        image: mysql:8.2
        container_name: database
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: calenduret
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        container_name: apache
        restart: on-failure
        build:
            context: ./php
        ports:
            - '8080:80'
        volumes:
            - './apache/default.conf:/etc/apache2/sites-enabled/000-default.conf'
            - './app:/var/www'
        depends_on:
            - database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: secret
            UPLOAD_LIMIT: 100M
        ports:
            - '8899:80'